This changes the icon of the reading list (glasses) to the star so it…
kiwix/kiwix-desktop pull request #1066
Opened 2024-03-21 16:53 UTC by sgourdas

This closes #605, by changing the reading list add/remove icon from the "glasses" to the "star" icon that is used in most places.
Also added a tooltip to signify the action about to be done.

2024-03-22 10:18 UTC, veloman-yunkan requested changes
Please rewrite your commit message so that the GitHub doesn't have to split the title with an ellipsis.

2024-03-22 10:18 UTC, veloman-yunkan commented on src/searchbar.cpp
> +            setToolTip(gt("Add to the reading list"));
Move this message into `resources/i18n/en.json` and update `resources/i18n/qqq.json`.

2024-03-22 10:18 UTC, veloman-yunkan commented on src/searchbar.cpp
> +            setToolTip(gt("Remove from the reading list"));
Same here

2024-03-25 15:15 UTC, sgourdas commented
@veloman-yunkan added the missed tooltip keys and also squashed commits to clean up the mess I made :)

2024-03-26 10:45 UTC, veloman-yunkan requested changes
Regarding the commit message - it should consist of a summary (or title) and an optional long description (or additional details). The latter is needed if the information in the summary is not enough. https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html is a more detailed guide to writing commit messages. The only thing in it that I don't fully agree with is the imperative form of the title, however it makes perfect sense if we assume that the title of the commit message is written (and thus the objective of a change is defined) before the code is actually changed. Yet I suspect that that rule rather tries to save a couple of characters which, for the 50-character length limit of the title, is quite sensible. 

Your commit message has a form of just the full description. You can easily convert it to meet the community expectations by:

1. Removing the `-` from the first line (thus making it a title rather than just an item in the unnumbered list of changes)
2. Adding an `Also:` line to the body of the message.

Thus it will read:

```
Changed icon of toggling page to reading list (glasses) to a star

Also:

- Added tooltip for add/remove on reading list
```

2024-03-26 10:45 UTC, veloman-yunkan commented on resources/i18n/qqq.json
> +	"remove-bookmark": "Represents the action of removing a page from the bookmarks",
Keys in `qqq.json` must match those in `en.json`. Actually these key names are better than the ones in `en.json`.

2024-03-27 11:35 UTC, veloman-yunkan requested changes
Please also squash your commits when you fix the new comment.

2024-03-27 11:35 UTC, veloman-yunkan commented on src/searchbar.cpp
> +            setToolTip(gt("remove-reading-list"));
You forgot to update the message keys here.

2024-03-27 16:43 UTC, veloman-yunkan reviewed
There are still two commits in your PR. Other than that it looks good.

2024-03-27 16:59 UTC, sgourdas commented
This was embarrassing... Going to study a bit on git... :)

At least I now understand what and where to look. LGTMBTWRE

2024-03-27 18:24 UTC, veloman-yunkan approved these changes
Great!

Let this PR be merged. But if you are fast enough you can fix/revert the commit message (to get rid of the ugly ellipsis because of the too long title)

2024-03-30 10:40 UTC, kelson42 requested changes
I think this PR suffers from many problem/weanesses (even if part of the problem might already have been there first):
* The pointer is not appropriate when over the icon, should be an arrow
* The icon is too small, should be significantly bigger to be easy to click
* To me the icon is also not centered properly, it seem to be aligned on the text base position on the right
* Default value is wrong, should not be "full" as per default pages are not bookmarked (I suspect both icons full/empty have been inverted)... tooltip also wrong like the icon.

2024-03-31 13:40 UTC, sgourdas commented
Regarding these issues:
- For me, when hovering over the icon the pointer is an arrow, same as other icons
- I agree. 32x32 looks right to me. How do you see it?
- Initially it seemed off to me as well. After making it bigger I think it looks normal, but would like a second opinion on if we should center it based on the searchbar height
- Fixed

2024-04-07 19:09 UTC, kelson42 commented
@sgourdas Kind of a miracle - as you don't have fixed all the points - but now everything looks good to me. Thank you!

2024-04-07 19:10 UTC, merged