Added --no-sandbox command line argument
kiwix/kiwix-desktop pull request #1170
Opened 2024-08-05 19:31 UTC by sgourdas

This aims to close #885 by adding the `--no-sandbox` command line argument.

This allows the user to manage the risk and turn off the sandbox for example when running from a network mounted drive on Windows.

Also, so as to apply the no sandbox flag before the KiwixApp has been instantiated, the argument check is being done with the usual way of checking `argv` instead of using `QCommandLineParser` which runs on `KiwixApp::a`.

2024-08-05 19:34 UTC, sgourdas commented
How should I test this since it is Windows specific? nightly?

2024-08-07 05:05 UTC, kelson42 commented
I guess we have no way to test this properly before mergin unfortunately.

2024-08-07 05:08 UTC, kelson42 requested changes
Please update the `usage()` so if we type `kiwix-desktop --help` we get a proper explanation. Regarding the parsing of the command line, we don't have already a lib, a place (already there) doing that properly?

2024-08-07 07:35 UTC, sgourdas commented
> Please update the usage() so if we type kiwix-desktop --help we get a proper explanation.

I am not sure I understand. What else should be populated?
<img width="653" alt="image" src="https://github.com/user-attachments/assets/2776e21f-969b-40e4-a111-2c7dddb89b42">

> Regarding the parsing of the command line, we don't have already a lib, a place (already there) doing that properly? We should be able to handle this in a better manner.

We do indeed, I assume you are talking about QCommandLinerParser. The issue is that it needs the app to be instantiated before it can check the parameters. In our case we need to check and apply the no sandbox variable before app init so this creates an issue. The only workaround I have found is creating a dummy `QCoreApplication` which I do not really like as a solution.

2024-08-07 09:18 UTC, veloman-yunkan reviewed
Do we really need the `--no-sandbox` option?

Under Windows, GUI applications are rarely started from the command line. Of course we can provide a wrapper bat file `kiwix-desktop-no-sandbox.bat` for starting `kiwix-desktop` in that mode, but then we can simply set the `QTWEBENGINE_CHROMIUM_FLAGS` env var in that script directly.

2024-08-07 20:30 UTC, kelson42 commented
I can only agree, we could/should better provide a `.bat` launcher. But by doing so, having a C++ piece of code.

In general, I don't like to provide necessary features to users via ENV because this is not clear/transparent and an error happens very easily without a chance to really detect it easily. But I get that here there is really a risk of overengineering if we provide a `.bat` launcher.

All in one, I believe I would still prefer to have this properly in C++, but whatever approach chosen at the end, this is not a blocker to me.

2024-08-07 20:39 UTC, kelson42 commented
> > Please update the usage() so if we type kiwix-desktop --help we get a proper explanation.
> 
> I am not sure I understand. What else should be populated? <img alt="image" width="653" src="https://private-user-images.githubusercontent.com/57002743/355706784-2776e21f-969b-40e4-a111-2c7dddb89b42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNjI0ODcsIm5iZiI6MTcyMzA2MjE4NywicGF0aCI6Ii81NzAwMjc0My8zNTU3MDY3ODQtMjc3NmUyMWYtOTY5Yi00MGU0LWExMTEtMmM3ZGRkYjg5YjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDIwMjMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMjAwODUwYjE1NWUyMjAwOGE1ZTM5NDQyYTk0ZDk5NzcyMTQ0NWUxOWRlODMwZjg2OTgyNDgxNGQ3YzkyM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LoyVcfpYAqc298PSwvhfwOcjufzrG-jXbc-swrPxik8">

Juste me been blind, sorry. Please add something like "Necessary to run Kiwix from Windows network drive." So this is clear why we have this option.

> > Regarding the parsing of the command line, we don't have already a lib, a place (already there) doing that properly? We should be able to handle this in a better manner.
> 
> We do indeed, I assume you are talking about QCommandLinerParser. The issue is that it needs the app to be instantiated before it can check the parameters. In our case we need to check and apply the no sandbox variable before app init so this creates an issue. The only workaround I have found is creating a dummy `QCoreApplication` which I do not really like as a solution.

OK, I let you see the details with @veloman-yunkan. LGTM then.

2024-08-07 20:40 UTC, kelson42 approved these changes
Looks good from user perspective (even if not tested on Windows)

2024-08-09 08:38 UTC, veloman-yunkan commented
> All in one, I believe I would still prefer to have this properly in C++, but whatever approach chosen at the end, this is not a blocker to me.

I would agree with a C++ implementation if it works as follows:

1. detects that `kiwix-desktop` is started from a network location,
2. tells the user about it and asks for confirmation to continue under relaxed security constraints.

Otherwise, given that we provide a `.bat` file (that will hide from the user how that issue is solved under the hood), I can't justify a command-line option being added to `kiwix-desktop`.

2024-08-09 08:42 UTC, kelson42 commented
> > All in one, I believe I would still prefer to have this properly in C++, but whatever approach chosen at the end, this is not a blocker to me.
> 
> I would agree with a C++ implementation if it works as follows:
> 
> 1. detects that `kiwix-desktop` is started from a network location,
> 2. tells the user about it and asks for confirmation to continue under relaxed security constraints.

@sgourdas doable?

2024-08-09 09:45 UTC, sgourdas commented
@kelson42, definitely. I think that since we only want to do this for Windows an easy and valid check should be checking the absolute filepath's prefix for `\\`

2024-08-09 09:54 UTC, veloman-yunkan commented
> @kelson42, definitely. I think that since we only want to do this for Windows an easy and valid check should be checking the absolute filepath's prefix for `\\`

This won't work for mapped network shares (that's the case of the ticket, their path starts with `Q:\`).

2024-08-09 10:08 UTC, sgourdas commented
> > @kelson42, definitely. I think that since we only want to do this for Windows an easy and valid check should be checking the absolute filepath's prefix for `\\`
> 
> This won't work for mapped network shares (that's the case of the ticket, their path starts with `Q:\`).

I can see. And I cannot really easily test it sadly. 

What seems like a more reliable way is [GetDriveType](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getdrivetypea) from `windows.h`. I will investigate and come back with a commit.

2024-08-09 10:53 UTC, sgourdas commented
@kelson42 @veloman-yunkan can we use nightly to test? Is there another option?

2024-08-09 13:39 UTC, veloman-yunkan commented
> @kelson42 @veloman-yunkan can we use nightly to test? Is there another option?

I think that you can clone the `kiwix-build` repository and modify the [ci](https://github.com/kiwix/kiwix-build/blob/main/.github/workflows/ci.yml) github flow and/or some other scripts so that it uses your branch of `kiwix-desktop`. This will build under Windows natively (via the MSVC compiler).

I think that it is also possible to cross-compile for Windows under Linux (using one of the `kiwix-build` options `--config win32_dyn` or `--config win32_static`).

2024-08-11 17:30 UTC, kelson42 commented
@veloman-yunkan We are really getting rid of cross-compilation and moving all compalition for Windows on Windows. This is something @mgautierfr has been working on since months.

2024-08-12 13:13 UTC, mgautierfr commented
> I think that it is also possible to cross-compile for Windows under Linux (using one of the kiwix-build options --config win32_dyn or --config win32_static).

Today we are building kiwix-desktop for windows only on the appveyor CI (as @kelson42 said, I'm working on it to be able to build it locally/in GH CI).
One with commit rights on kiwix-build can trigger a test build of kiwix-desktop with commits like the last two ones in https://github.com/kiwix/kiwix-build/tree/build_dev_kiwix-desktop
(This also means that a build of this PR will be available soon in https://tmp.kiwix.org/ci/dev_preview/build_dev_kiwix-desktop/)

2024-08-14 17:06 UTC, kelson42 commented
All of this is far two complicated. I merge and we will see. The solution is clearly to have:
* An easy compilation on Windows (relying on a prebuild of libkiwix/libzim)
* A Windows CI in this repo.

2024-08-14 17:13 UTC, merged