Monitor data directory on portable mode
kiwix/kiwix-desktop pull request #1209
Opened 2024-09-13 13:42 UTC by sgourdas

This simplifies the creation of a portable USB by automatically monitoring the data directory in portable mode.

Fixes #461

2024-09-14 12:34 UTC, kelson42 approved these changes
LGTM from user perspective

2024-09-15 16:19 UTC, kelson42 commented
@sgourdas Might that be that settings UI about monitoring directory should be greyed, as any value will be overriden at start by the code?

2024-09-16 08:38 UTC, veloman-yunkan approved these changes

2024-09-16 14:47 UTC, sgourdas commented
@kelson42 sure, but should that be the case only for the monitor directory?

2024-09-16 18:44 UTC, kelson42 commented
@sgourdas Yes, I think so... because whatever this settings is set it will be reseted at start right? For the other settings, the user can change them and they will be kept!

2024-09-16 19:00 UTC, sgourdas commented
> @sgourdas Yes, I think so... because whatever this settings is set it will be reseted at start right? For the other settings, the user can change them and they will be kept!

No, that is not the case at the moment per this commit. Monitor **and** download directory are currently hardcoded to the data directory on **every portable start**.

What would the desired behavior be?

2024-09-16 19:21 UTC, kelson42 commented
> > @sgourdas Yes, I think so... because whatever this settings is set it will be reseted at start right? For the other settings, the user can change them and they will be kept!
> 
> 
> 
> @kelson42 no, that is not the case at the moment per this commit. Monitor **and** download directory are currently hardcoded to the data directory on **every portable start**.
> 
> 
> 
> What would the desired behavior be?

Then I guess both should be greyed in portable mode (only).

2024-09-17 10:13 UTC, sgourdas commented
> > > @sgourdas Yes, I think so... because whatever this settings is set it will be reseted at start right? For the other settings, the user can change them and they will be kept!
> > 
> > 
> > @kelson42 no, that is not the case at the moment per this commit. Monitor **and** download directory are currently hardcoded to the data directory on **every portable start**.
> > What would the desired behavior be?
> 
> Then I guess both should be greyed in portable mode (only).

@kelson42 I added immutability on these two in portable mode. It includes grayed out text, disabled buttons and tooltip to explain the disabling.

2024-09-17 11:42 UTC, kelson42 commented
@sgourdas LGTM, please rebase so we can proceed with merging.

2024-09-17 12:42 UTC, veloman-yunkan requested changes

2024-09-17 12:42 UTC, veloman-yunkan commented on resources/i18n/en.json
> +    "portable-disabled-tooltip": "Function disabled in portable mode",
qqq.json must be updated too

2024-09-17 12:42 UTC, veloman-yunkan commented on src/settingsview.cpp
> +        ui->monitorClear->setToolTip(gt("portable-disabled-tooltip"));
Please rewrite this fragment in a shorter way after introducing the following helper function in an unnamed namespace

```c++
void disableInPortableMode(QWidget* w)
{
        w->setEnabled(false); 
        QString disabledStyle = "color: gray;";
        w->setStyleSheet(disabledStyle);
        w->setToolTip(gt("portable-disabled-tooltip"));
}
```

2024-09-17 13:08 UTC, veloman-yunkan approved these changes

2024-09-17 13:32 UTC, merged