Workaround for strange libkiwix-dev dependency issue
kiwix/kiwix-desktop pull request #1288
Opened 2024-12-17 14:35 UTC by veloman-yunkan

Should fix #1285

For some mysterious reason the dependency requirement "libkiwix-dev (>= 14.0.0)" in the Debian control file results in PPA build failure. After unpacking `kiwix-build-deps_2.4.0~focal_all.deb` the 'apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes install -f' commands reports:

    Reading package lists...
    Building dependency tree...
    Reading state information...
    Starting pkgProblemResolver with broken count: 1
    Starting 2 pkgProblemResolver with broken count: 1
    Investigating (0) kiwix-build-deps:amd64 < 2.4.0~focal @iU mK Nb Ib >
    Broken kiwix-build-deps:amd64 Depends on libkiwix-dev:amd64 < none -> 14.0.0~focal @un uN > (>= 14.0.0)
      Removing kiwix-build-deps:amd64 because I can't find libkiwix-dev:amd64
    Done

Shortening the libkiwix-dev minimal version string to "14.0" (libkiwix-dev (>= 14.0)) works around that issue.

2024-12-17 14:56 UTC, veloman-yunkan commented
After this PR is merged the 2.4.0 release tag has to be moved.

2024-12-18 05:05 UTC, kelson42 requested changes
@veloman-yunkan Thx for this strange finding and fix. To me -whatever we do, we should be coherent how we represent the upper version bound and the lower one. So I would prefer to have "15.0".

2024-12-18 06:43 UTC, veloman-yunkan commented
The lower and upper bound versions of the libzim dependency have been shortened too for consistency.

2024-12-18 06:52 UTC, kelson42 commented
@veloman-yunkan Thx. On my side I would be ready to merge, but lets try to understand first why it was working on dev.

2024-12-18 08:27 UTC, kelson42 commented
OK, then I merge because we need to have `2.4` in the PPA to complete the release process.

2024-12-18 08:28 UTC, merged