Fixed #543 : Added a feature: Alt + <digit> to switch between tabs.
kiwix/kiwix-desktop pull request #567
Opened 2020-12-30 12:23 UTC by rishabh-soni

Resolved #543 - I made different Actions for each individual key sequence (Alt + 1, Alt +2,..) namely ToggleTab1Action, ToggleTab2Action.. and so on.

2021-01-06 17:16 UTC, asashnov commented
A better approach could be
* creating a subclass from QAction, for example, `SetCurrentTabAction`;
* Passing name, hotkey, index (0-9), and a pointer to the main window to the constructor;
*  we can make those actions 'hidden' to not show them in Menu;
* in receiving slot, we can use  qobject_cast<SetCurrentTabAction*>(sender())  and if this is not nullptr, get the needed tab index from it.

2021-01-13 11:55 UTC, kelson42 commented
@rishabh-soni Any update?

2021-01-13 13:12 UTC, rishabh-soni commented
Yeah I am working on it 👍

2021-01-13 14:28 UTC, asashnov commented
Just realized the more easy approach: we can use QAction::data() with the tab number

2021-01-16 09:25 UTC, kelson42 commented
@rishabh-soni Hopefuly the last comment by @asashnov will help you to complete this PR. Otherwise please let us know.

2021-01-21 14:40 UTC, kelson42 commented
@rishabh-soni Any news here? We plan to do a release soon and it would be great to have your PR inside.

2021-01-21 15:18 UTC, rishabh-soni commented
Oh I see, actually my mid semester exams have begun and the last exam is on 1st Feb. So can you give me a deadline or time till 2nd or 3rd Feb?

2021-01-22 07:37 UTC, kelson42 commented
3rd of february is OK.

2021-02-03 14:48 UTC, rishabh-soni commented
I am trying to implement the sub-classing QAction approach as said, but I am new to this framework, so I am having a hard time figuring out how would I extract (I am not sure if that would be the right word to say here) the number which was passed along with the 'alt' key? Can anyone please give me a hint or a source from which I can see some example of a similar implementation?

2021-02-03 21:13 UTC, kelson42 commented
@asashnov ?

2021-02-25 15:07 UTC, asashnov commented
@rishabh-soni  No need to subclass `QAction`, just use `QAction::data()`. Here is an example:

```c
MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    for (int i = 0 ; i < ui->tabWidget->count() ; i++) {
        QAction *a = new QAction(this);
        a->setText(QString("Switch to tab %1").arg(i+1));
        a->setData(QVariant::fromValue(i));
        QKeySequence ks(Qt::ALT | (Qt::Key_1 + i));
        a->setShortcut(ks);
        addAction(a);
        connect(a, SIGNAL(triggered()), this, SLOT(switch_to_tab_by_triggered_action()));
    }
}

void MainWindow::switch_to_tab_by_triggered_action()
{
    QAction *a = qobject_cast<QAction*>(QObject::sender());
    if (!a)
        return;

    bool ok;
    int tab_n = a->data().toInt(&ok);

    if (!ok)
        return;
    if (tab_n >= ui->tabWidget->count())
        return;

    ui->tabWidget->setCurrentIndex(tab_n);
}
```

To run this example, just create a new Qt Widget Application project in QtCreator, put QTabWidget into MainWindow, and add this code. The whole project is here:

[SwitchingTabs.zip](https://github.com/kiwix/kiwix-desktop/files/6043833/SwitchingTabs.zip)

2021-02-25 15:16 UTC, asashnov reviewed
Probably we don't have to use CREATE_ACTION macros for Alt+<N> shortcuts.

2021-02-25 15:16 UTC, asashnov commented on src/kiwixapp.cpp
> +    SET_SHORTCUT(ToggleTab7Action, QKeySequence(Qt::ALT + Qt::Key_7));
Maybe Qt::AltModifier | Qt::Key_7  is a better option, according to
 https://doc.qt.io/qt-5/qt.html#KeyboardModifier-enum

2021-02-25 15:50 UTC, rishabh-soni commented
Thanks a lot, I'll implement this as soon as possible 👍🏼

2021-03-04 05:50 UTC, kelson42 commented
@rishabh-soni any news?

2021-03-04 21:33 UTC, rishabh-soni commented
Done! Thanks a lot @asashnov, now I have made the required changes using QAction::data(). Please have a look now at my commit.

2021-03-05 06:15 UTC, kelson42 commented
@rishabh-soni Great, so this is not a draft PR anymore?

2021-03-05 06:20 UTC, kelson42 commented
@rishabh-soni You could i believe rebase your branch on git origin master, that would be better.

2021-03-05 09:39 UTC, asashnov requested changes

2021-03-05 09:39 UTC, asashnov commented on kiwix-desktop.pro.user
> +<?xml version="1.0" encoding="UTF-8"?>
.pro.user file is local for every developer's machine, no need to commit it to repository

2021-03-05 09:39 UTC, asashnov commented on src/mainmenu.cpp
> -
I like this extra line to logically separate blocks of code. As we don't modify any code in this file, let's just exclude it from this PR.

2021-03-05 09:39 UTC, asashnov commented on src/tabbar.h
> -
This empty line visually separates properties definition from methods. So let's keep it.

2021-03-05 09:39 UTC, asashnov commented on src/tabbar.cpp
> -                this->createNewTab(true);
@mgautierfr  Do we have any code convention on Kiwix Desktop project? If not, I suggest using Qt's convention: https://wiki.qt.io/Coding_Conventions#Lambdas

2021-03-05 16:38 UTC, kelson42 commented
@rishabh-soni Please reopen the PR... and be carefuly with force pushing, you might loose your code if you don't take care.

2021-03-05 17:03 UTC, rishabh-soni commented
Yeah just give me some time I had made a backup of my code so I'll restore it shortly.

2021-03-05 19:34 UTC, rishabh-soni commented
@asashnov @kelson42 Please have a look now, I have updated my fork and all the spaces and empty lines which were previously in the code are restored now. By mistake I force pushed the re based branch into my fork.

2021-03-07 06:13 UTC, asashnov approved these changes
Looks good and works, well done!

2021-03-07 06:55 UTC, merged