add version and help commandline options
kiwix/kiwix-desktop pull request #631
Opened 2021-05-02 15:58 UTC by HanYoung-uwu

As requested by #602

2021-05-02 18:18 UTC, kelson42 commented
@HanYoung-uwu Thank you very much

2021-05-17 10:03 UTC, mgautierfr requested changes
Just a small change. Everything else is good.

2021-05-17 10:03 UTC, mgautierfr commented on src/main.cpp
> +#define STR(X) _STR(X)
We don't need this, it is already in `src/kiwixapp.h`

2021-05-19 09:23 UTC, HanYoung-uwu commented
force pushed

2021-05-19 12:27 UTC, merged