FileDialog style and other efficiency fixes
kiwix/kiwix-desktop pull request #634
Opened 2021-05-03 15:02 UTC by HanYoung-uwu

Setting windows style on non-windows platform makes FileDialog looks hideous. 
![Default style](https://user-images.githubusercontent.com/76819220/116892791-c95cb280-ac62-11eb-86d1-ece16de1fd89.png)
![After set the Windows style](https://user-images.githubusercontent.com/76819220/116892795-ca8ddf80-ac62-11eb-8949-ca6b13e533bb.png)

Note that "Windows" style is not what you usually want even if you like windows style. "QWindowsVistaStyle" is what people usually choose. 

Other changes include:
* Avoid extra copy on `KiwixApp::openZimFile`
* Remove `close()` on QFile because it close file in destructor, call it here you pay one more check on destructing (and extra line of code)

2021-05-03 19:11 UTC, kelson42 commented
I see no visible change on Ubuntu, I guess this impacts only Windows users.

2021-05-04 05:08 UTC, HanYoung-uwu commented
> I see no visible change on Ubuntu, I guess this impacts only Windows users.

Well, this does impact me who is on Arch/KDE.

2021-05-13 14:05 UTC, HanYoung-uwu commented
> I see no visible change on Ubuntu, I guess this impacts only Windows users.

Is your filedialog like the second picture above?

2021-05-14 08:05 UTC, kelson42 commented
@HanYoung-uwu This is how it looks like for me 
![image](https://user-images.githubusercontent.com/1029718/118240968-dfa51280-b49b-11eb-951b-3e523b878c58.png)

2021-05-16 07:41 UTC, HanYoung-uwu commented
> @HanYoung-uwu This is how it looks like for me
> ![image](https://user-images.githubusercontent.com/1029718/118240968-dfa51280-b49b-11eb-951b-3e523b878c58.png)

So in your case, QFileDialog opens native filedialog using XDG, your native filedialog is gnome so Qt style doesn't affect you. But for system which native filedialog is written in Qt, ugly windows theme is used.

2021-05-17 12:53 UTC, mgautierfr requested changes
Two small changes on the git commits.
Noting to say on the code itself.

---

> Remove close() on QFile because it close file in destructor, call it here you pay one more check on destructing (and extra line of code)

This comment could be put in the commit message itself
("Don't close the QFile explicitly as it will be close anyway in the destructor.")

2021-05-17 12:53 UTC, mgautierfr commented on src/kiwixapp.cpp
> +        _zimfile = QDir::toNativeSeparators(_zimfile);
This change should be made in previous commit.

2021-05-18 08:25 UTC, HanYoung-uwu commented
force pushed. Please re-review

2021-05-18 09:14 UTC, mgautierfr approved these changes

2021-05-18 09:14 UTC, mgautierfr commented
We are good. Thanks !

2021-05-18 09:14 UTC, merged