Detect and add new zim files from Download Dir into local library
kiwix/kiwix-desktop pull request #712
Opened 2021-11-01 12:34 UTC by juuz0

Fixes #644

2021-11-01 15:17 UTC, kelson42 requested changes
For me, unfortunately does not work. I have downloaded a ZIM file manuaylly in `/home/kelson/.local/share/kiwix` which is my profile directory but it does not appear in the Kiwix-Desktop after I restarted it... but I can add the file manuallly.

2021-11-02 03:17 UTC, juuz0 commented
@kelson42 
Which is that zim file?
I tried with a couple of more files and both work for me.

(Maybe its some different language file and will only show up after choosing All files in the left-side panel?)

2021-11-02 06:28 UTC, kelson42 commented
It is not a filter problem.

2021-11-02 07:34 UTC, kelson42 commented
@mgautierfr Does it work for you?

2021-11-03 13:30 UTC, mgautierfr commented
> Does it work for you?

It works. But it takes time. The function has to parse all the directory and open all new zim files before you see changes in the UI.

2021-11-03 13:57 UTC, mgautierfr requested changes
This PR works but there are still few things to change.

@veloman-yunkan is working on live updating the library with issue kiwix/kiwix-tools#243
It would be better than you see with him what is the best way to do this (and not implement twice the same thing).
It may even worth it to delay this PR until the work on kiwix/kiwix-tools#243 is finished its work on the libkiwix side.

@veloman-yunkan, what do you think about this ?

2021-11-03 13:57 UTC, mgautierfr commented on src/library.cpp
> +            save();
It would be better to create only one Manager, and save the library at the end of the process.

2021-11-03 13:57 UTC, mgautierfr commented on src/library.cpp
> +            kiwix::Manager manager(&m_library);
It is better to create a `LibraryManipulator` and create the manager on this manipulator. (As it is made in the `Library` creator).
This way, the manipulator emit the `booksChanged` signal at every new book added and the UI is update as soon as possible.

2021-11-03 13:57 UTC, mgautierfr commented on src/kiwixapp.cpp
> +    });
We have to be careful with multithreading. The library is not thread safe, so you must protect it from multiple call with a mutex.

2021-11-03 14:34 UTC, kelson42 commented
Tested it again... an now it works... I probably made an error the first time I tested.

2021-11-21 16:23 UTC, kelson42 commented
@juuz0 Thank you for your patience on this. We have discussed this PR with @mgautierfr. What is sure is that:
* This topic is at the crossroad of meany topics
* Even if we tend to agree on the whole concept this is still not printed in the stone
* Your code depends on the capacity of the libkiwix to easily refresh the library and @veloman-yunkan is currently working on this with https://github.com/kiwix/libkiwix/pull/636.

For all these reasons, we would like to wait the code update code in libkiwix is ready. That wait it would avoid you have to reimplement part of it by yourself. Then we could focus on the pure feature aspect of this PR.

2021-11-21 17:46 UTC, juuz0 commented
@kelson42 Yes thanks for the update! Library reloading will be nice when done :)

2021-12-11 04:57 UTC, juuz0 commented
Closing in favour of #743

2021-12-11 04:57 UTC, closed without merging