Added functionality to open new tabs right after current tab.
kiwix/kiwix-desktop pull request #716
Opened 2021-11-03 16:28 UTC by juuz0

Fixes #636

2021-11-03 17:26 UTC, mgautierfr requested changes
Just a small change in the parameter name and we can merge.

2021-11-03 17:26 UTC, mgautierfr commented on src/tabbar.cpp
> +ZimView* TabBar::createNewTab(bool setCurrent, bool adjacentToPreviousTab)
It may be better to name the argument `adjacentToCurrentTab`

2021-11-04 03:18 UTC, juuz0 commented
Should I squash?

2021-11-04 09:24 UTC, mgautierfr commented
> Should I squash?

Yes please. The two commits are not two intermediate steps. The second is a fix for the first one. So no need to keep both changes separated (but it was nice to have the two commits to simplify the review)

2021-11-04 09:28 UTC, juuz0 commented
Alright, done.

2021-11-04 09:50 UTC, mgautierfr approved these changes

2021-11-04 09:51 UTC, mgautierfr commented
I've rebased and fix the conflict.

2021-11-04 09:57 UTC, merged