Improvements to Settings Panel
kiwix/kiwix-desktop pull request #719
Opened 2021-11-12 02:42 UTC by juuz0

Fixes #718

2021-11-12 08:58 UTC, kelson42 approved these changes
From a user perspective, it works as expeted. Thx!

2021-11-15 09:14 UTC, mgautierfr requested changes
We are good on the code.

I would prefer a better commit message however.
The current one is a bit to general and do not say what is done.
You can think of the commit title (the first line) as a description of what is done and what will be put in the Changelog.
It would be better to have something like "Change existing tab's zoom when setting's zoom is changed"

---

The same way (but it is to be pedantic, and I will not block the PR for this), as you are doing two different, unrelated things (change the labeling and change the behavior), it would have been nice to have two commits.

2021-11-15 19:18 UTC, juuz0 commented
Thank you for the suggestions! I have followed them (and also learned how to split a commit into 2 xD)

2021-11-16 09:04 UTC, mgautierfr approved these changes

2021-11-16 09:28 UTC, merged