Remove space before colon and question mark in strings
kiwix/kiwix-desktop pull request #724
Opened 2021-11-18 08:49 UTC by amire80

Space is necessary before ':' and '?' in the French language,
but it's not necessary in English and in most other languages.

2021-11-18 09:24 UTC, mgautierfr requested changes

2021-11-18 09:24 UTC, mgautierfr commented on resources/i18n/en.json
> +    "download-dir-dialog-title":"Are you sure you want to change the download directory",
You have removed the question mark with the space.

2021-11-18 09:32 UTC, amire80 commented
:facepalm: 

I put the question mark back. Thanks for the careful review! :)

2021-11-18 12:58 UTC, kelson42 commented
Actually, and this is something we agreed with @juuz0, to me we should remove the colon character on the settings panel.

2021-11-21 16:45 UTC, kelson42 commented
Thanks @amire80 for your PR, I have taken the essence of it in #725.

2021-11-21 16:45 UTC, closed without merging

2021-11-21 16:58 UTC, amire80 commented
Thanks!