Add fullscreen support to ZIM files
kiwix/kiwix-desktop pull request #777
Opened 2022-01-30 19:29 UTC by juuz0

Fixes #571

2022-02-01 07:56 UTC, kelson42 requested changes
@juuz0 Feature works fine, but seems to me incomplete. Would you be able to show full window (but without window decoration) when mouse in on top of screen like on Firefox? This is important because otherwise we might have easily users stuck in fullscreen.

2022-02-01 16:57 UTC, juuz0 commented
> This is important because otherwise we might have easily users stuck in fullscreen.

Agreed, haha. Somehow I missed implementing that. On it.

2022-02-11 17:59 UTC, juuz0 commented on src/tabbar.h
> +    void toggleFullscreen();
Overlooked it, thanks. Will fix it

2022-02-15 16:02 UTC, kelson42 commented
@juuz0 Any chance this PR could go through next review iteration before the end of the week? Otherwise I will have probably to move it to milestone 2.3.0.

2022-02-15 17:11 UTC, juuz0 commented
@kelson42 Yes, in the next 24 hours :+1:

2022-02-17 08:40 UTC, juuz0 commented
>  Would you be able to show full window (but without window decoration) when mouse in on top of screen like on Firefox? 

Done, also rebased.

You can review but I want to ask - should the ZIM's fullscreen (but don't keep window decoration) be removed on pressing the fulltext search command shortcut (Ctrl L, for me) and then after search is done, back to fullscreen.

2022-02-17 08:40 UTC, juuz0 commented
Whoa, what happened to CI

2022-02-17 10:08 UTC, kelson42 requested changes
@juuz0 This does not behave like it should, tobar/tabs headers appears now when you put your mouse on the top of the screen but:
* They don't disappear after a while
* It seems you actualy leave the fulltscreen mode, but you still does not display the window decoration.
* There is somehow a flash

This is not like it work for Firefox for example, look at it to better understand what is expected please.

2022-06-25 16:41 UTC, kelson42 commented
@juuz0 What should we do with this PR?

2022-06-26 06:56 UTC, juuz0 commented
@kelson42  I will re-review this and let you know by today :+1:

2022-07-04 21:17 UTC, kelson42 commented
@juuz0 Any news here?

2022-07-05 17:04 UTC, juuz0 commented
@kelson42 I forgot most of what I did earlier, but now I've re reviewed :+1: Thanks for the ping

Curently, what I am doing is:

- Put current webview in fullscreenwindow
- When mouse is moved to top of screen, remove fullscreenwindow and put MainScreen in full screen (this change is the cause of a "flash") - this is to mimic Firefox's behaviour which shows tabs on bringing mouse to top of screen.

What this lacks:
- [in Firefox] When mouse is brought to top of screen and tab is changed by mouse click, the new tab is also made fullscreen. Doesn't happen with this PR, I've tried implementing but it becomes a mesh with flashes. Not good.
-  Turn back to fullscreen mode when mouse is not on top of screen. Easy to do but flashes will become a problem.
- Firefox's minimize, maximize, exit buttons are on the same line as tabs, here we don't. So how could they be shown? Or we don't show them?

The current implementation doesn't look right.
My thinking on Firefox's implementation is that it puts the application in fullscreen and then hides/unhides the tabs part, maybe that should be done. This red part will get toggled for visibility.
![image](https://user-images.githubusercontent.com/26814569/177378318-e131ee44-f507-4b6d-abec-8302de306cdb.png)

Do you have some other way to implement this? @mgautierfr

2022-07-12 11:08 UTC, juuz0 commented
Closing in favour of #859

2022-07-12 11:10 UTC, closed without merging