Move asyncLoadMonitorDir in ContentManager
kiwix/kiwix-desktop pull request #803
Opened 2022-02-26 15:18 UTC by juuz0

This gives it the ability to use m_local and only make changes when local library is in use.
Not causing repeated refreshes while downloading - if the monitor directory is set same as download directory

2022-02-27 04:15 UTC, juuz0 commented
@kelson42 No, I can't reproduce #802 with http://download.kiwix.org/nightly/2022-02-26/kiwix-desktop_windows_x64_2022-02-26.zip. I should mention that the changes from https://github.com/kiwix/kiwix-desktop/pull/800  are introduced in nightly, 2022-02-26 (which OP hasn't tried), they could've fixed it.

This PR fixes an OS independent issue :)

2022-02-27 16:32 UTC, kelson42 requested changes
I believe to not understand all the rationals behind this PR. It seems to be an optimization of the code which is in `master` to save the software many refresh efforts (when the local library is not displayed).

On the principle, I can only praise such an effort and I have tested it. Unfortunately this bring at least one regression:
* Monitore the Download directory and put a `toto.zim` file
* It appears in the local library properly
* Go to online library
* Rename `toto.zim` to `toto.zim.hidden`
* Got to local library. The `toto.zim` entry is still there and it should not anymore (wchih is the case with `master`).

With the little I understand, the principle of the this optimisation seems somehow weak. Maybe a clearer split should be made between (1) update the internal library (2) update the visual part.

2022-02-27 19:34 UTC, juuz0 commented
> Got to local library. The toto.zim entry is still there and it should not anymore (wchih is the case with master).

Fixed

2022-02-28 07:14 UTC, kelson42 requested changes
Seems now totally broken to me: does not detect new files and does not detect removed files

2022-03-03 07:02 UTC, juuz0 commented
@kelson42 Superseded by #811

2022-03-03 07:02 UTC, closed without merging