Filter out service worker based content from the online library
kiwix/kiwix-desktop pull request #887
Opened 2022-09-18 14:55 UTC by kelson42

Fixes https://github.com/kiwix/kiwix-desktop/issues/780 and superseeds #870

2022-09-24 18:46 UTC, kelson42 commented
@mgautierfr  @veloman-yunkan Can I merge this?

2022-09-25 14:14 UTC, juuz0 requested changes
Unfortunately, doesn't work for me, file still shows up in my library.
This is the file
https://drive.google.com/file/d/1e_sSHD86NI6u7A-LetWW1C6Ap16w1p2d/view?usp=sharing

2022-09-25 14:31 UTC, kelson42 commented
Yes, this is for the online library only. To me this is good enough. If someone wants really to load one, and use it with HTTP daemon, then it should be possible. This is why I have talked of OPDS stream in the ticket, but thiscwad not super specific indeed.

2022-09-25 17:53 UTC, veloman-yunkan approved these changes

2022-09-25 18:57 UTC, merged