Add random icon on top widget
kiwix/kiwix-desktop pull request #928
Opened 2023-03-10 12:07 UTC by juuz0

Fixes #896 
![image](https://user-images.githubusercontent.com/26814569/224311990-a55f7b50-a6cd-491b-9b90-33213d35eca4.png)

Reversed:
![image](https://user-images.githubusercontent.com/26814569/224312066-f4e80560-8ff0-4698-8e40-90afbde58feb.png)

2023-03-27 21:49 UTC, kelson42 commented
@juuz0 Thank you for the PR, sorry for the lack of feedback. We will have a look.

2023-03-28 12:28 UTC, veloman-yunkan approved these changes

2023-03-29 13:40 UTC, mgautierfr commented
Not an issue introduced by this PR (it was there already), but it would be nice to "deactivate" the action when random is not relevant (for example in the library view).

2023-03-30 08:16 UTC, kelson42 commented
@juuz0 Last remark from @mgautierfr is pertinent. Can you please secure the icon is greyed/unsable when necessary?

2023-03-30 08:17 UTC, kelson42 requested changes
almost good

2023-03-30 12:36 UTC, juuz0 commented
Done.
![image](https://user-images.githubusercontent.com/26814569/228837641-4bbb740d-8f70-4755-ba15-ff428a4c0e14.png)
![image](https://user-images.githubusercontent.com/26814569/228837691-a4b762af-4217-4248-a7e0-83acbff521e9.png)

2023-03-30 13:19 UTC, kelson42 approved these changes
LGTM. THX!

2023-03-30 13:19 UTC, merged